[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=x86-64-v3"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-cpu=x86-64-v3"]
