// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function Convert(arg1:string,arg2:string):Promise<main.ConvertResultJSON>;

export function Export(arg1:string):Promise<string>;

export function Greet():Promise<string>;

export function Search(arg1:string):Promise<Array<db.Anime>>;
