// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2) {
  return window['go']['main']['App']['Convert'](arg1, arg2);
}

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
