// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AnimeDatabase,
    ConsolidatedMetadata,
    DatabaseEntry,
    DatabaseInfo,
    ExportResult,
    MatchListResult,
    MatchOptions,
    MatchQueryOptions,
    MatchResult,
    MatchSelection,
    ScoreBreakdown,
    ScoredCandidate,
    SearchItem,
    SearchOptions,
    SearchResult,
    ShindenEntry,
    ShindenList,
    ShindenMatchResult,
    TitleMetadata
} from "./models.js";

import * as $models from "./models.js";

/**
 * @typedef {$models.OptionalFloat} OptionalFloat
 */
