// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DatabaseInfo {
    /**
     * Creates a new DatabaseInfo instance.
     * @param {Partial<DatabaseInfo>} [$$source = {}] - The source object to create the DatabaseInfo.
     */
    constructor($$source = {}) {
        if (!("lastUpdate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastUpdate"] = "";
        }
        if (!("release" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseInfo(/** @type {Partial<DatabaseInfo>} */($$parsedSource));
    }
}
