// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as anime$0 from "../anime/models.js";

export const DatabaseInfo = anime$0.DatabaseInfo;

/**
 * @typedef {anime$0.DatabaseInfo} DatabaseInfo
 */

export const ShindenList = anime$0.ShindenList;

/**
 * @typedef {anime$0.ShindenList} ShindenList
 */
